// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddHistoryRecord(arg1:backend.HistoryRecord):Promise<void>;

export function DeleteAIHistoryRecord(arg1:string):Promise<void>;

export function DeleteBank(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DownloadImageAndSaveHistory(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Record<string, any>):Promise<string>;

export function EnsureBank(arg1:string,arg2:backend.BankItem):Promise<void>;

export function EnsureTemplate(arg1:backend.Template):Promise<void>;

export function GenerateImage(arg1:backend.GenerateRequest):Promise<backend.GenerateResponse>;

export function GetConfig():Promise<backend.ConfigResponse>;

export function GetProviders():Promise<backend.ProvidersResponse>;

export function GetUserDownloadDir():Promise<string>;

export function LoadAIHistory():Promise<Array<backend.HistoryRecord>>;

export function LoadBanks():Promise<backend.BankMap>;

export function LoadCategories():Promise<backend.CategoryMap>;

export function LoadTemplates():Promise<Array<backend.Template>>;

export function ReadImageFile(arg1:string):Promise<string>;

export function SaveAIHistory(arg1:Array<backend.HistoryRecord>):Promise<void>;

export function SaveBanks(arg1:backend.BankMap):Promise<void>;

export function SaveImageFile(arg1:Array<number>,arg2:string):Promise<void>;

export function SaveTemplates(arg1:Array<backend.Template>):Promise<void>;

export function SelectReferenceImages(arg1:boolean):Promise<Array<string>>;

export function SetConfig(arg1:backend.ConfigRequest):Promise<void>;

export function SetTemplateCover(arg1:string,arg2:string):Promise<string>;
