// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistoryRecord(arg1) {
  return window['go']['backend']['App']['AddHistoryRecord'](arg1);
}

export function DeleteAIHistoryRecord(arg1) {
  return window['go']['backend']['App']['DeleteAIHistoryRecord'](arg1);
}

export function DeleteBank(arg1) {
  return window['go']['backend']['App']['DeleteBank'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['backend']['App']['DeleteTemplate'](arg1);
}

export function DownloadImageAndSaveHistory(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['DownloadImageAndSaveHistory'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function EnsureBank(arg1, arg2) {
  return window['go']['backend']['App']['EnsureBank'](arg1, arg2);
}

export function EnsureTemplate(arg1) {
  return window['go']['backend']['App']['EnsureTemplate'](arg1);
}

export function GenerateImage(arg1) {
  return window['go']['backend']['App']['GenerateImage'](arg1);
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetProviders() {
  return window['go']['backend']['App']['GetProviders']();
}

export function GetUserDownloadDir() {
  return window['go']['backend']['App']['GetUserDownloadDir']();
}

export function LoadAIHistory() {
  return window['go']['backend']['App']['LoadAIHistory']();
}

export function LoadBanks() {
  return window['go']['backend']['App']['LoadBanks']();
}

export function LoadCategories() {
  return window['go']['backend']['App']['LoadCategories']();
}

export function LoadTemplates() {
  return window['go']['backend']['App']['LoadTemplates']();
}

export function ReadImageFile(arg1) {
  return window['go']['backend']['App']['ReadImageFile'](arg1);
}

export function SaveAIHistory(arg1) {
  return window['go']['backend']['App']['SaveAIHistory'](arg1);
}

export function SaveBanks(arg1) {
  return window['go']['backend']['App']['SaveBanks'](arg1);
}

export function SaveImageFile(arg1, arg2) {
  return window['go']['backend']['App']['SaveImageFile'](arg1, arg2);
}

export function SaveTemplates(arg1) {
  return window['go']['backend']['App']['SaveTemplates'](arg1);
}

export function SelectReferenceImages(arg1) {
  return window['go']['backend']['App']['SelectReferenceImages'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['backend']['App']['SetConfig'](arg1);
}

export function SetTemplateCover(arg1, arg2) {
  return window['go']['backend']['App']['SetTemplateCover'](arg1, arg2);
}
